name: CD - Deployment to Flyio

on:
# Currently disabled to avoid accidental break of our app 
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  workflow_dispatch:   # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Install Fly CLI
      - name: Install Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          export PATH="$HOME/.fly/bin:$PATH"

      # Deploy to Fly.io
      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: fly deploy --app ece1779-project-online-gaming-platform

